name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1]
        stability: [prefer-lowest, prefer-stable]
        actions:
          - { name: PHPStan, run: vendor/bin/phpstan analyse --no-progress --error-format=github }
          - { name: PHPUnit, run: vendor/bin/phpunit --teamcity, teamcity: true }

    name: ${{ matrix.actions.name }} (PHP ${{ matrix.php }} - ${{ matrix.stability }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmul
          coverage: pcov

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Configure Teamcity matcher
        if: ${{ matrix.actions.teamcity }}
        uses: mheap/phpunit-matcher-action@v1

      - name: Run ${{ matrix.actions.name }}
        run: ${{ matrix.actions.run }}

# @TODO: Consider adding this!
#      - name: Code coverage
#        if: ${{ github.ref == 'refs/heads/master' && github.repository == 'thephpleague/oauth2-server' }}
#        run: |
#          wget https://scrutinizer-ci.com/ocular.phar
#          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
